### ISSUE TITLE
Export modules only in node

### ISSUE THREAD

**Issue by arrested-developer** [FACxBeamery/project-week-2#11]
https://github.com/FACxBeamery/project-week-2/blob/6969fd382ed41e4b7a63819b42887393a083862e/pureFunctions.js#L8-L11

You can add an if statement so that the `module.exports` only happens in node for your tests - it's not required in the browser

```
 if (typeof module !== 'undefined' && typeof module.exports !== 'undefined') {
    module.exports = myModule;
}
```

**Comment by Joaoviana** [comment]
This was exactly what I was looking for!! 🤯
